#%RAML 1.0
title: MULE 4 API Playground
version: 0.0.1
mediaType: application/json
description: |
  API specification for the Mule 4 API Playground

/http-resources:
  get:
     responses:
      200:
        description: "Success"
  
  post:
     responses:
      201:
        description: "Success"
  
  /{id}:

    delete:
       responses:
        204:
          description: "Success"
        404:
          description: "Failed"
    
    get:
       responses:
        200:
          description: "Success"
        404:
          description: "Failed"
    
    patch:
       responses:
        200:
          description: "Success"
        204:
          description: "Success"
        404:
          description: "Failed"

    put:
       responses:
        200:
          description: "Success"
        204:
          description: "Success"
        404:
          description: "Failed"

/soap-resources:
  get:
     responses:
      200:
        description: "Success"
  
  post:
     responses:
      201:
        description: "Success"
  
  /{id}:

    delete:
       responses:
        204:
          description: "Success"
        404:
          description: "Failed"
    
    get:
       responses:
        200:
          description: "Success"
        404:
          description: "Failed"
    
    patch:
       responses:
        200:
          description: "Success"
        204:
          description: "Success"
        404:
          description: "Failed"

    put:
       responses:
        200:
          description: "Success"
        204:
          description: "Success"
        404:
          description: "Failed"

/ftp-resources:
  get:
     responses:
      200:
        description: "Success"
  
  post:
     responses:
      201:
        description: "Success"
  
  /{id}:

    delete:
       responses:
        204:
          description: "Success"
        404:
          description: "Failed"
    
    get:
       responses:
        200:
          description: "Success"
        404:
          description: "Failed"
    
    patch:
       responses:
        200:
          description: "Success"
        204:
          description: "Success"
        404:
          description: "Failed"

    put:
       responses:
        200:
          description: "Success"
        204:
          description: "Success"
        404:
          description: "Failed"

/sftp-resources:
  get:
     responses:
      200:
        description: "Success"
  
  post:
     responses:
      201:
        description: "Success"
  
  /{id}:

    delete:
       responses:
        204:
          description: "Success"
        404:
          description: "Failed"
    
    get:
       responses:
        200:
          description: "Success"
        404:
          description: "Failed"
    
    patch:
       responses:
        200:
          description: "Success"
        204:
          description: "Success"
        404:
          description: "Failed"

    put:
       responses:
        200:
          description: "Success"
        204:
          description: "Success"
        404:
          description: "Failed"